alter session set NLS_DATE_FORMAT='DD-MM-YYYY';
commit;

insert into address (unit_no, street_name, city, province, postal_code, country) values (820, 'Manley', 'Nanaimo', 'British Columbia', 'V6L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (55, 'West', 'Armstrong', 'British Columbia', 'M9R2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (408, 'Towne', 'Duncan', 'British Columbia', 'V9L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (8523, '6th', 'Langford', 'British Columbia', 'V9C2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (630, 'Reinke', 'Sicamous', 'British Columbia', 'G2L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (2914, 'Farmco', 'Logan Lake', 'British Columbia', 'T3S2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (7492, 'Goodland', 'Okanagan', 'British Columbia', 'T0P2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (6982, 'Warrior', 'Lillooet', 'British Columbia', 'H9G2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (0438, 'Sunnyside', 'New Westminster', 'British Columbia', 'V4C2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (12, 'Valley Edge', 'Ladysmith', 'British Columbia', 'V9G2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (6398, 'Surrey', 'Summerland', 'British Columbia', 'H1V2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (95569, 'Golf Course', 'Kimberley', 'British Columbia', 'V1A2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (29148, 'Northridge', 'Lillooet', 'British Columbia', 'H9G2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (387, 'Oriole', 'Maple Ridge', 'British Columbia', 'V2X2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (83, 'East', 'Lumby', 'British Columbia', 'P7L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (0, 'Scoville', 'Chilliwack', 'British Columbia', 'N5L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (69, 'Bayside', 'Burns Lake', 'British Columbia', 'M4H2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (4162, 'Mccormick', 'Maple Ridge', 'British Columbia', 'V2X2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (5329, 'Manley', 'Duncan', 'British Columbia', 'V9L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (43444, 'Arrowood', 'Houston', 'British Columbia', 'T9G2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (465, 'Hansons', 'West End', 'British Columbia', 'V7Y2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (46701, 'Shelley', 'Lions Bay', 'British Columbia', 'K4K2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (0, 'Hoard', 'Logan Lake', 'British Columbia', 'T3S2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (62079, 'Lunder', 'Port Moody', 'British Columbia', 'V3H2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (0528, 'Sutherland', 'Bowen Island', 'British Columbia', 'V7W2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (82793, 'Dovetail', 'Nakusp', 'British Columbia', 'H9A2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (205, 'New Castle', 'Hope', 'British Columbia', 'V7R2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (32, 'Cottonwood', 'Oliver', 'British Columbia', 'E5L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (96635, 'Sunbrook', 'Abbotsford', 'British Columbia', 'L9T2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (5, 'Dapin', 'West End', 'British Columbia', 'V7Y2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (77817, 'Springview', 'North Saanich', 'British Columbia', 'K6A2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (7, 'Coleman', 'North Cowichan', 'British Columbia', 'V9L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (869, 'Mandrake', 'Ladysmith', 'British Columbia', 'V9G2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (961, 'Jay', 'Oliver', 'British Columbia', 'E5L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (4, 'Maywood', 'New Westminster', 'British Columbia', 'V4C2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (822, 'Glendale', 'Lillooet', 'British Columbia', 'H9G2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (6294, 'Scott', 'Victoria', 'British Columbia', 'V9A2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (6045, 'Darwin', 'White Rock', 'British Columbia', 'V4B2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (028, 'La Follette', 'Osoyoos', 'British Columbia', 'N9V2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (986, 'Monica', 'Aldergrove', 'British Columbia', 'V4W2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (90673, 'Pankratz', 'Oliver', 'British Columbia', 'E5L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (63609, 'Raven', 'Sicamous', 'British Columbia', 'G2L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (90, 'Burrows', 'Abbotsford', 'British Columbia', 'L9T2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (9213, 'Badeau', 'Richmond', 'British Columbia', 'V6Y2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (35, 'Green Ridge', 'Chase', 'British Columbia', 'H4R2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (0, 'Del Mar', 'Summerland', 'British Columbia', 'H1V2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (7, 'Kinsman', 'Lumby', 'British Columbia', 'P7L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (44242, 'Twin Pines', 'Duncan', 'British Columbia', 'V9L2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (28964, 'Elmside', 'Parksville', 'British Columbia', 'V9P2A1', 'Canada');
insert into address (unit_no, street_name, city, province, postal_code, country) values (19932, 'Crownhardt', 'Kamloops', 'British Columbia', 'H9P2A1', 'Canada');
commit work;
