insert into contains (description, customer_id, order_no) values ('Re-engineered well-modulated installation', 1, 01);
insert into contains (description, customer_id, order_no) values ('Focused contextually-based open architecture', 2, 02);
insert into contains (description, customer_id, order_no) values ('Streamlined client-driven hierarchy', 3, 03);
insert into contains (description, customer_id, order_no) values ('Visionary transitional solution', 4, 04);
insert into contains (description, customer_id, order_no) values ('Total bandwidth-monitored policy', 5, 05);
insert into contains (description, customer_id, order_no) values ('Proactive zero tolerance synergy', 6, 06);
insert into contains (description, customer_id, order_no) values ('Cross-group tertiary moratorium', 7, 07);
insert into contains (description, customer_id, order_no) values ('Secured demand-driven leverage', 8, 08);
insert into contains (description, customer_id, order_no) values ('Re-contextualized zero administration task-force', 9, 09);
insert into contains (description, customer_id, order_no) values ('User-friendly multimedia local area network', 10, 010);
insert into contains (description, customer_id, order_no) values ('Reverse-engineered 6th generation encoding', 11, 011);
insert into contains (description, customer_id, order_no) values ('Open-source bifurcated service-desk', 12, 012);
insert into contains (description, customer_id, order_no) values ('Organized eco-centric methodology', 13, 013);
insert into contains (description, customer_id, order_no) values ('Sharable non-volatile adapter', 14, 014);
insert into contains (description, customer_id, order_no) values ('Advanced fault-tolerant knowledge user', 15, 015);
insert into contains (description, customer_id, order_no) values ('Horizontal full-range matrix', 16, 016);
insert into contains (description, customer_id, order_no) values ('Programmable bottom-line framework', 17, 017);
insert into contains (description, customer_id, order_no) values ('Synergistic interactive initiative', 18, 018);
insert into contains (description, customer_id, order_no) values ('Cross-platform tertiary infrastructure', 19, 019);
insert into contains (description, customer_id, order_no) values ('Big Blue TV', 50, 020);
insert into contains (description, customer_id, order_no) values ('Big comfy couch', 50, 21);
insert into contains (description, customer_id, order_no) values ('Hockey Stick', 50, 22);
insert into contains (description, customer_id, order_no) values ('Yellow Dog', 50, 23);
insert into contains (description, customer_id, order_no) values ('All toys', 50, 24);
insert into contains (description, customer_id, order_no) values ('Green den', 50, 25);

commit work;
