insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (142, 'Kin Barnett', 'Male', '40-5336357', '6 Warner Way', 41774);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (165, 'Vanessa Longshaw', 'Female', '73-6665934', '42 Hayes Trail', 41774);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (196, 'Evelina Girt', 'Female', '29-9088976', '8 Maywood Place', 7509);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (163, 'Aleen Labin', 'Female', '93-0755254', '66407 Barby Drive', 7509);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (175, 'Carola Proback', 'Female', '81-4994128', '88 Emmet Trail', 7509);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (120, 'Allx Caberas', 'Female', '02-9085312', '672 Dahle Lane', 41774);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (145, 'Annetta Straughan', 'Female', '90-8105587', '13 Hoffman Place', 41774);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (131, 'Jammie Lovekin', 'Female', '50-7475414', '15 Vahlen Avenue', 41774);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (191, 'Bobbee Bythway', 'Female', '97-5126927', '99 Debs Avenue', 41774);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (101, 'Nita Hutchinson', 'Female', '66-2474597', '1 Esker Trail', 59);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (168, 'Cirilo Cready', 'Male', '01-9283205', '36 American Ash Trail', 7509);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (155, 'Hedvig Klimschak', 'Female', '74-9943035', '02 Crownhardt Drive', 41774);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (167, 'Eilis Kesley', 'Female', '99-2873125', '28809 Florence Avenue', 41774);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (184, 'Ricard Gaskamp', 'Male', '71-5634578', '4 Crest Line Lane', 41774);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (164, 'Boris Myner', 'Male', '93-4355010', '8788 Dayton Hill', 7509);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (182, 'Virgie Hargreave', 'Female', '61-1654972', '0 Amoth Point', 41774);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (126, 'Johanna Babber', 'Female', '67-6838680', '80761 Scott Point', 7509);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (137, 'Alric Leckie', 'Male', '49-6052332', '38 Lotheville Junction', 59);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (106, 'Rickie Nunan', 'Male', '04-4113811', '89891 Walton Lane', 59);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (121, 'Tressa Chisholm', 'Female', '07-4475586', '58067 Hollow Ridge Plaza', 7509);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (113, 'Windham Frusher', 'Male', '00-1799534', '40 Iowa Way', 59);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (157, 'Lorne Stourton', 'Female', '53-7397332', '61 Golf View Road', 59);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (158, 'Harman Ferebee', 'Male', '29-9661105', '18975 Bashford Way', 59);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (128, 'Augusto Elsmore', 'Male', '37-9919122', '66 Eagle Crest Hill', 85784);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (140, 'Gerrard Caudrey', 'Male', '35-1120861', '069 Sauthoff Crossing', 85784);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (148, 'Jamey Millery', 'Male', '89-8579426', '2668 La Follette Center', 85784);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (189, 'Frankie Beauman', 'Male', '26-8202065', '281 Hanson Center', 85784);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (169, 'Leroi Dudin', 'Male', '56-8135724', '05 Anthes Center', 85784);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (118, 'Jerrine Maurice', 'Female', '96-8874599', '9 Loomis Circle', 85784);
insert into employee_works (employee_id, employee_name, employee_gender, employee_sin, employee_address, branch_id) values (180, 'Madlen Robel', 'Female', '86-7975621', '29793 Clarendon Avenue', 85784);
commit work;
