insert into lives (unit_no, street_name, city, customer_id) values (820, 'Manley', 'Nanaimo', 1);
insert into lives (unit_no, street_name, city, customer_id) values (55, 'West', 'Armstrong', 2);
insert into lives (unit_no, street_name, city, customer_id) values (408, 'Towne', 'Duncan', 3);
insert into lives (unit_no, street_name, city, customer_id) values (8523, '6th', 'Langford', 4);
insert into lives (unit_no, street_name, city, customer_id) values (630, 'Reinke', 'Sicamous', 5);
insert into lives (unit_no, street_name, city, customer_id) values (2914, 'Farmco', 'Logan Lake', 6);
insert into lives (unit_no, street_name, city, customer_id) values (7492, 'Goodland', 'Okanagan', 7);
insert into lives (unit_no, street_name, city, customer_id) values (6982, 'Warrior', 'Lillooet', 8);
insert into lives (unit_no, street_name, city, customer_id) values (0438, 'Sunnyside', 'New Westminster', 9);
insert into lives (unit_no, street_name, city, customer_id) values (12, 'Valley Edge', 'Ladysmith', 10);
insert into lives (unit_no, street_name, city, customer_id) values (6398, 'Surrey', 'Summerland', 11);
insert into lives (unit_no, street_name, city, customer_id) values (95569, 'Golf Course', 'Kimberley', 12);
insert into lives (unit_no, street_name, city, customer_id) values (29148, 'Northridge', 'Lillooet', 13);
insert into lives (unit_no, street_name, city, customer_id) values (387, 'Oriole', 'Maple Ridge', 14);
insert into lives (unit_no, street_name, city, customer_id) values (83, 'East', 'Lumby', 15);
insert into lives (unit_no, street_name, city, customer_id) values (0, 'Scoville', 'Chilliwack', 16);
insert into lives (unit_no, street_name, city, customer_id) values (69, 'Bayside', 'Burns Lake', 17);
insert into lives (unit_no, street_name, city, customer_id) values (4162, 'Mccormick', 'Maple Ridge', 18);
insert into lives (unit_no, street_name, city, customer_id) values (5329, 'Manley', 'Duncan', 19);
insert into lives (unit_no, street_name, city, customer_id) values (43444, 'Arrowood', 'Houston', 20);
insert into lives (unit_no, street_name, city, customer_id) values (465, 'Hansons', 'West End', 21);
insert into lives (unit_no, street_name, city, customer_id) values (46701, 'Shelley', 'Lions Bay', 22);
insert into lives (unit_no, street_name, city, customer_id) values (0, 'Hoard', 'Logan Lake', 23);
insert into lives (unit_no, street_name, city, customer_id) values (62079, 'Lunder', 'Port Moody', 24);
insert into lives (unit_no, street_name, city, customer_id) values (0528, 'Sutherland', 'Bowen Island', 25);
insert into lives (unit_no, street_name, city, customer_id) values (82793, 'Dovetail', 'Nakusp', 26);
insert into lives (unit_no, street_name, city, customer_id) values (205, 'New Castle', 'Hope', 27);
insert into lives (unit_no, street_name, city, customer_id) values (32, 'Cottonwood', 'Oliver', 28);
insert into lives (unit_no, street_name, city, customer_id) values (96635, 'Sunbrook', 'Abbotsford', 29);
insert into lives (unit_no, street_name, city, customer_id) values (5, 'Dapin', 'West End', 30);
insert into lives (unit_no, street_name, city, customer_id) values (77817, 'Springview', 'North Saanich', 31);
insert into lives (unit_no, street_name, city, customer_id) values (7, 'Coleman', 'North Cowichan', 32);
insert into lives (unit_no, street_name, city, customer_id) values (869, 'Mandrake', 'Ladysmith', 33);
insert into lives (unit_no, street_name, city, customer_id) values (961, 'Jay', 'Oliver', 34);
insert into lives (unit_no, street_name, city, customer_id) values (4, 'Maywood', 'New Westminster', 35);
insert into lives (unit_no, street_name, city, customer_id) values (822, 'Glendale', 'Lillooet', 36);
insert into lives (unit_no, street_name, city, customer_id) values (6294, 'Scott', 'Victoria', 37);
insert into lives (unit_no, street_name, city, customer_id) values (6045, 'Darwin', 'White Rock', 38);
insert into lives (unit_no, street_name, city, customer_id) values (028, 'La Follette', 'Osoyoos', 39);
insert into lives (unit_no, street_name, city, customer_id) values (986, 'Monica', 'Aldergrove', 40);
insert into lives (unit_no, street_name, city, customer_id) values (90673, 'Pankratz', 'Oliver', 41);
insert into lives (unit_no, street_name, city, customer_id) values (63609, 'Raven', 'Sicamous', 42);
insert into lives (unit_no, street_name, city, customer_id) values (90, 'Burrows', 'Abbotsford', 43);
insert into lives (unit_no, street_name, city, customer_id) values (9213, 'Badeau', 'Richmond', 44);
insert into lives (unit_no, street_name, city, customer_id) values (35, 'Green Ridge', 'Chase', 45);
insert into lives (unit_no, street_name, city, customer_id) values (0, 'Del Mar', 'Summerland', 46);
insert into lives (unit_no, street_name, city, customer_id) values (7, 'Kinsman', 'Lumby', 47);
insert into lives (unit_no, street_name, city, customer_id) values (44242, 'Twin Pines', 'Duncan', 48);
insert into lives (unit_no, street_name, city, customer_id) values (28964, 'Elmside', 'Parksville', 49);
insert into lives (unit_no, street_name, city, customer_id) values (19932, 'Crownhardt', 'Kamloops', 50);

insert into lives (unit_no, street_name, city, customer_id) values (55, 'West', 'Armstrong', 1);
insert into lives (unit_no, street_name, city, customer_id) values (408, 'Towne', 'Duncan', 1);
insert into lives (unit_no, street_name, city, customer_id) values (8523, '6th', 'Langford', 1);
insert into lives (unit_no, street_name, city, customer_id) values (630, 'Reinke', 'Sicamous', 1);
insert into lives (unit_no, street_name, city, customer_id) values (2914, 'Farmco', 'Logan Lake', 1);
insert into lives (unit_no, street_name, city, customer_id) values (7492, 'Goodland', 'Okanagan', 1);
insert into lives (unit_no, street_name, city, customer_id) values (6982, 'Warrior', 'Lillooet', 1);
insert into lives (unit_no, street_name, city, customer_id) values (0438, 'Sunnyside', 'New Westminster', 1);
insert into lives (unit_no, street_name, city, customer_id) values (12, 'Valley Edge', 'Ladysmith', 1);
insert into lives (unit_no, street_name, city, customer_id) values (6398, 'Surrey', 'Summerland', 1);
insert into lives (unit_no, street_name, city, customer_id) values (95569, 'Golf Course', 'Kimberley', 1);
insert into lives (unit_no, street_name, city, customer_id) values (29148, 'Northridge', 'Lillooet', 1);
insert into lives (unit_no, street_name, city, customer_id) values (387, 'Oriole', 'Maple Ridge', 1);
insert into lives (unit_no, street_name, city, customer_id) values (83, 'East', 'Lumby', 1);
insert into lives (unit_no, street_name, city, customer_id) values (0, 'Scoville', 'Chilliwack', 1);
insert into lives (unit_no, street_name, city, customer_id) values (69, 'Bayside', 'Burns Lake', 1);
insert into lives (unit_no, street_name, city, customer_id) values (4162, 'Mccormick', 'Maple Ridge', 1);
insert into lives (unit_no, street_name, city, customer_id) values (5329, 'Manley', 'Duncan', 1);
insert into lives (unit_no, street_name, city, customer_id) values (43444, 'Arrowood', 'Houston', 1);
insert into lives (unit_no, street_name, city, customer_id) values (465, 'Hansons', 'West End', 1);
insert into lives (unit_no, street_name, city, customer_id) values (46701, 'Shelley', 'Lions Bay', 1);
insert into lives (unit_no, street_name, city, customer_id) values (0, 'Hoard', 'Logan Lake', 1);
insert into lives (unit_no, street_name, city, customer_id) values (62079, 'Lunder', 'Port Moody', 1);
insert into lives (unit_no, street_name, city, customer_id) values (0528, 'Sutherland', 'Bowen Island', 1);
insert into lives (unit_no, street_name, city, customer_id) values (82793, 'Dovetail', 'Nakusp', 1);
insert into lives (unit_no, street_name, city, customer_id) values (205, 'New Castle', 'Hope', 1);
insert into lives (unit_no, street_name, city, customer_id) values (32, 'Cottonwood', 'Oliver', 1);
insert into lives (unit_no, street_name, city, customer_id) values (96635, 'Sunbrook', 'Abbotsford', 1);
insert into lives (unit_no, street_name, city, customer_id) values (5, 'Dapin', 'West End', 1);
insert into lives (unit_no, street_name, city, customer_id) values (77817, 'Springview', 'North Saanich', 1);
insert into lives (unit_no, street_name, city, customer_id) values (7, 'Coleman', 'North Cowichan', 1);
insert into lives (unit_no, street_name, city, customer_id) values (869, 'Mandrake', 'Ladysmith', 1);
insert into lives (unit_no, street_name, city, customer_id) values (961, 'Jay', 'Oliver', 1);
insert into lives (unit_no, street_name, city, customer_id) values (4, 'Maywood', 'New Westminster', 1);
insert into lives (unit_no, street_name, city, customer_id) values (822, 'Glendale', 'Lillooet', 1);
insert into lives (unit_no, street_name, city, customer_id) values (6294, 'Scott', 'Victoria', 1);
insert into lives (unit_no, street_name, city, customer_id) values (6045, 'Darwin', 'White Rock', 1);
insert into lives (unit_no, street_name, city, customer_id) values (028, 'La Follette', 'Osoyoos', 1);
insert into lives (unit_no, street_name, city, customer_id) values (986, 'Monica', 'Aldergrove', 1);
insert into lives (unit_no, street_name, city, customer_id) values (90673, 'Pankratz', 'Oliver', 1);
insert into lives (unit_no, street_name, city, customer_id) values (63609, 'Raven', 'Sicamous', 1);
insert into lives (unit_no, street_name, city, customer_id) values (90, 'Burrows', 'Abbotsford', 1);
insert into lives (unit_no, street_name, city, customer_id) values (9213, 'Badeau', 'Richmond', 1);
insert into lives (unit_no, street_name, city, customer_id) values (35, 'Green Ridge', 'Chase', 1);
insert into lives (unit_no, street_name, city, customer_id) values (0, 'Del Mar', 'Summerland', 1);
insert into lives (unit_no, street_name, city, customer_id) values (7, 'Kinsman', 'Lumby', 1);
insert into lives (unit_no, street_name, city, customer_id) values (44242, 'Twin Pines', 'Duncan', 1);
insert into lives (unit_no, street_name, city, customer_id) values (28964, 'Elmside', 'Parksville', 1);
insert into lives (unit_no, street_name, city, customer_id) values (19932, 'Crownhardt', 'Kamloops', 1);

insert into lives (unit_no, street_name, city, customer_id) values (820, 'Manley', 'Nanaimo', 2);
insert into lives (unit_no, street_name, city, customer_id) values (408, 'Towne', 'Duncan', 2);
insert into lives (unit_no, street_name, city, customer_id) values (8523, '6th', 'Langford', 2);
insert into lives (unit_no, street_name, city, customer_id) values (630, 'Reinke', 'Sicamous', 2);
insert into lives (unit_no, street_name, city, customer_id) values (2914, 'Farmco', 'Logan Lake', 2);
insert into lives (unit_no, street_name, city, customer_id) values (7492, 'Goodland', 'Okanagan', 2);
insert into lives (unit_no, street_name, city, customer_id) values (6982, 'Warrior', 'Lillooet', 2);
insert into lives (unit_no, street_name, city, customer_id) values (0438, 'Sunnyside', 'New Westminster', 2);
insert into lives (unit_no, street_name, city, customer_id) values (12, 'Valley Edge', 'Ladysmith', 2);
insert into lives (unit_no, street_name, city, customer_id) values (6398, 'Surrey', 'Summerland', 2);
insert into lives (unit_no, street_name, city, customer_id) values (95569, 'Golf Course', 'Kimberley', 2);
insert into lives (unit_no, street_name, city, customer_id) values (29148, 'Northridge', 'Lillooet', 2);
insert into lives (unit_no, street_name, city, customer_id) values (387, 'Oriole', 'Maple Ridge', 2);
insert into lives (unit_no, street_name, city, customer_id) values (83, 'East', 'Lumby', 2);
insert into lives (unit_no, street_name, city, customer_id) values (0, 'Scoville', 'Chilliwack', 2);
insert into lives (unit_no, street_name, city, customer_id) values (69, 'Bayside', 'Burns Lake', 2);
insert into lives (unit_no, street_name, city, customer_id) values (4162, 'Mccormick', 'Maple Ridge', 2);
insert into lives (unit_no, street_name, city, customer_id) values (5329, 'Manley', 'Duncan', 2);
insert into lives (unit_no, street_name, city, customer_id) values (43444, 'Arrowood', 'Houston', 2);
insert into lives (unit_no, street_name, city, customer_id) values (465, 'Hansons', 'West End', 2);
insert into lives (unit_no, street_name, city, customer_id) values (46701, 'Shelley', 'Lions Bay', 2);
insert into lives (unit_no, street_name, city, customer_id) values (0, 'Hoard', 'Logan Lake', 2);
insert into lives (unit_no, street_name, city, customer_id) values (62079, 'Lunder', 'Port Moody', 2);
insert into lives (unit_no, street_name, city, customer_id) values (0528, 'Sutherland', 'Bowen Island', 2);
insert into lives (unit_no, street_name, city, customer_id) values (82793, 'Dovetail', 'Nakusp', 2);
insert into lives (unit_no, street_name, city, customer_id) values (205, 'New Castle', 'Hope', 2);
insert into lives (unit_no, street_name, city, customer_id) values (32, 'Cottonwood', 'Oliver', 2);
insert into lives (unit_no, street_name, city, customer_id) values (96635, 'Sunbrook', 'Abbotsford', 2);
insert into lives (unit_no, street_name, city, customer_id) values (5, 'Dapin', 'West End', 2);
insert into lives (unit_no, street_name, city, customer_id) values (77817, 'Springview', 'North Saanich', 2);
insert into lives (unit_no, street_name, city, customer_id) values (7, 'Coleman', 'North Cowichan', 2);
insert into lives (unit_no, street_name, city, customer_id) values (869, 'Mandrake', 'Ladysmith', 2);
insert into lives (unit_no, street_name, city, customer_id) values (961, 'Jay', 'Oliver', 2);
insert into lives (unit_no, street_name, city, customer_id) values (4, 'Maywood', 'New Westminster', 2);
insert into lives (unit_no, street_name, city, customer_id) values (822, 'Glendale', 'Lillooet', 2);
insert into lives (unit_no, street_name, city, customer_id) values (6294, 'Scott', 'Victoria', 2);
insert into lives (unit_no, street_name, city, customer_id) values (6045, 'Darwin', 'White Rock', 2);
insert into lives (unit_no, street_name, city, customer_id) values (028, 'La Follette', 'Osoyoos', 2);
insert into lives (unit_no, street_name, city, customer_id) values (986, 'Monica', 'Aldergrove', 2);
insert into lives (unit_no, street_name, city, customer_id) values (90673, 'Pankratz', 'Oliver', 2);
insert into lives (unit_no, street_name, city, customer_id) values (63609, 'Raven', 'Sicamous', 2);
insert into lives (unit_no, street_name, city, customer_id) values (90, 'Burrows', 'Abbotsford', 2);
insert into lives (unit_no, street_name, city, customer_id) values (9213, 'Badeau', 'Richmond', 2);
insert into lives (unit_no, street_name, city, customer_id) values (35, 'Green Ridge', 'Chase', 2);
insert into lives (unit_no, street_name, city, customer_id) values (0, 'Del Mar', 'Summerland', 2);
insert into lives (unit_no, street_name, city, customer_id) values (7, 'Kinsman', 'Lumby', 2);
insert into lives (unit_no, street_name, city, customer_id) values (44242, 'Twin Pines', 'Duncan', 2);
insert into lives (unit_no, street_name, city, customer_id) values (28964, 'Elmside', 'Parksville', 2);
insert into lives (unit_no, street_name, city, customer_id) values (19932, 'Crownhardt', 'Kamloops', 2);
commit work;
