insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (01, 'Standard', 'Karrah', '06/04/2018', 17, '325 Forest Pass', 142);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (02, 'Standard', 'Carita', '09/12/2017', 16, '892 Clyde Gallagher Trail', 165);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (03, 'Priority', 'Silvain', '21/07/2017', 17, '13 Talmadge Center', 196);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (04, 'Express', 'Bethany', '01/06/2018', 17, '4 Memorial Road', 163);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (05, 'Standard', 'Verne', '28/04/2018', 12, '85374 Waubesa Pass', 175);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (06, 'Standard', 'Davita', '03/04/2018', 24, '6 Magdeline Drive', 120);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (07, 'Priority', 'Dare', '20/03/2018', 27, '84545 Ruskin Hill', 145);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (08, 'Standard', 'Normy', '26/07/2017', 22, '97873 Utah Plaza', 131);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (09, 'Standard', 'Danell', '25/10/2017', 30, '77039 Sunfield Hill', 180);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (010, 'Priority', 'Rakel', '16/05/2018', 13, '0 Paget Avenue', 118);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (011, 'Priority', 'Fanchon', '29/12/2017', 6, '4 Kropf Junction', 189);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (012, 'Standard', 'Felipe', '26/10/2017', 20, '389 Anzinger Crossing', 169);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (013, 'Standard', 'Neron', '02/04/2018', 26, '4 Quincy Park', 158);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (014, 'Standard', 'Abel', '27/06/2017', 27, '1451 Butterfield Road', 148);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (015, 'Standard', 'Berkie', '28/12/2017', 30, '444 Holmberg Junction', 140);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (016, 'Priority', 'Christen', '03/10/2017', 23, '168 Rigney Pass', 128);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (017, 'Standard', 'Marleah', '30/08/2017', 14, '2248 Arrowood Park', 157);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (018, 'Standard', 'Meade', '24/09/2017', 18, '598 4th Avenue', 113);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (019, 'Standard', 'Kimberly', '07/03/2018', 23, '033 Jenna Parkway', 121);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (020, 'Standard', 'Natalya', '18/07/2017', 14, '63837 Hoffman Place', 106);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (21, 'Express','Graiden','01/09/18',5,'6428 Enim Avenue', 142);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (22, 'Express','Kirsten','16/12/17',8,'4611 Fermentum Street', 165);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (23, 'Express','Lester','22/10/17',7,'6973 Eros Street', 196);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (24, 'Express','Roary','19/12/17',9,'2904 Phasellus Rd.', 163);
insert into order_delivers (order_no, delivery_method, receiver, start_date, delivery_days, address, employee_id) values (25, 'Express','Colin','08/01/17',10,'3098 Porttitor St', 142);

commit work;
