insert into parcel_owns (weight, volume, description, customer_id) values (85.782, 10, 'Re-engineered well-modulated installation', 1);
insert into parcel_owns (weight, volume, description, customer_id) values (96.168, 68, 'Focused contextually-based open architecture', 2);
insert into parcel_owns (weight, volume, description, customer_id) values (95.957, 81, 'Streamlined client-driven hierarchy', 3);
insert into parcel_owns (weight, volume, description, customer_id) values (47.3, 37, 'Visionary transitional solution', 4);
insert into parcel_owns (weight, volume, description, customer_id) values (89.897, 60, 'Total bandwidth-monitored policy', 5);
insert into parcel_owns (weight, volume, description, customer_id) values (61.57, 31, 'Proactive zero tolerance synergy', 6);
insert into parcel_owns (weight, volume, description, customer_id) values (19.981, 41, 'Cross-group tertiary moratorium', 7);
insert into parcel_owns (weight, volume, description, customer_id) values (30.228, 79, 'Secured demand-driven leverage', 8);
insert into parcel_owns (weight, volume, description, customer_id) values (90.14, 33, 'Re-contextualized zero administration task-force', 9);
insert into parcel_owns (weight, volume, description, customer_id) values (31.361, 61, 'User-friendly multimedia local area network', 10);
insert into parcel_owns (weight, volume, description, customer_id) values (67.775, 8, 'Reverse-engineered 6th generation encoding', 11);
insert into parcel_owns (weight, volume, description, customer_id) values (97.627, 84, 'Open-source bifurcated service-desk', 12);
insert into parcel_owns (weight, volume, description, customer_id) values (94.491, 41, 'Organized eco-centric methodology', 13);
insert into parcel_owns (weight, volume, description, customer_id) values (19.024, 74, 'Sharable non-volatile adapter', 14);
insert into parcel_owns (weight, volume, description, customer_id) values (77.894, 90, 'Advanced fault-tolerant knowledge user', 15);
insert into parcel_owns (weight, volume, description, customer_id) values (30.175, 43, 'Horizontal full-range matrix', 16);
insert into parcel_owns (weight, volume, description, customer_id) values (78.731, 21, 'Programmable bottom-line framework', 17);
insert into parcel_owns (weight, volume, description, customer_id) values (45.193, 54, 'Synergistic interactive initiative', 18);
insert into parcel_owns (weight, volume, description, customer_id) values (37.463, 41, 'Cross-platform tertiary infrastructure', 19);
insert into parcel_owns (weight, volume, description, customer_id) values (67.568, 70, 'Enhanced system-worthy adapter', 20);
insert into parcel_owns (weight, volume, description, customer_id) values (16.733, 21, 'Ergonomic static time-frame', 21);
insert into parcel_owns (weight, volume, description, customer_id) values (80.505, 35, 'Devolved bandwidth-monitored support', 22);
insert into parcel_owns (weight, volume, description, customer_id) values (36.246, 69, 'Monitored asynchronous matrix', 23);
insert into parcel_owns (weight, volume, description, customer_id) values (95.525, 30, 'Virtual bottom-line local area network', 24);
insert into parcel_owns (weight, volume, description, customer_id) values (80.758, 27, 'Advanced zero administration function', 25);
insert into parcel_owns (weight, volume, description, customer_id) values (44.616, 14, 'Profound heuristic database', 26);
insert into parcel_owns (weight, volume, description, customer_id) values (38.847, 87, 'Horizontal incremental moderator', 27);
insert into parcel_owns (weight, volume, description, customer_id) values (11.285, 9, 'Expanded web-enabled structure', 28);
insert into parcel_owns (weight, volume, description, customer_id) values (25.259, 47, 'Multi-channelled maximized Graphic Interface', 29);
insert into parcel_owns (weight, volume, description, customer_id) values (40.502, 87, 'Customizable upward-trending workforce', 30);
insert into parcel_owns (weight, volume, description, customer_id) values (55.949, 2, 'Seamless reciprocal budgetary management', 31);
insert into parcel_owns (weight, volume, description, customer_id) values (30.522, 58, 'Organic explicit ability', 32);
insert into parcel_owns (weight, volume, description, customer_id) values (26.199, 97, 'Triple-buffered homogeneous budgetary management', 33);
insert into parcel_owns (weight, volume, description, customer_id) values (18.488, 4, 'Inverse responsive moderator', 34);
insert into parcel_owns (weight, volume, description, customer_id) values (98.746, 49, 'Decentralized empowering Graphic Interface', 35);
insert into parcel_owns (weight, volume, description, customer_id) values (54.154, 52, 'Implemented secondary adapter', 36);
insert into parcel_owns (weight, volume, description, customer_id) values (81.166, 33, 'Fundamental radical matrix', 37);
insert into parcel_owns (weight, volume, description, customer_id) values (93.022, 13, 'Multi-layered multimedia conglomeration', 38);
insert into parcel_owns (weight, volume, description, customer_id) values (95.337, 3, 'Reduced maximized collaboration', 39);
insert into parcel_owns (weight, volume, description, customer_id) values (30.235, 58, 'Object-based actuating portal', 40);
insert into parcel_owns (weight, volume, description, customer_id) values (73.234, 30, 'Proactive encompassing collaboration', 41);
insert into parcel_owns (weight, volume, description, customer_id) values (57.489, 16, 'Organized disintermediate capability', 42);
insert into parcel_owns (weight, volume, description, customer_id) values (10.803, 79, 'Virtual high-level process improvement', 43);
insert into parcel_owns (weight, volume, description, customer_id) values (86.393, 65, 'Polarised 6th generation initiative', 44);
insert into parcel_owns (weight, volume, description, customer_id) values (61.431, 34, 'Secured stable hierarchy', 45);
insert into parcel_owns (weight, volume, description, customer_id) values (94.2, 27, 'Persistent 5th generation Graphical User Interface', 46);
insert into parcel_owns (weight, volume, description, customer_id) values (58.561, 32, 'Fundamental 5th generation approach', 47);
insert into parcel_owns (weight, volume, description, customer_id) values (74.373, 47, 'Realigned intangible core', 48);
insert into parcel_owns (weight, volume, description, customer_id) values (56.352, 37, 'Mandatory mobile challenge', 49);
insert into parcel_owns (weight, volume, description, customer_id) values (9.57, 34, 'Big Blue TV', 50);
insert into parcel_owns (weight, volume, description, customer_id) values (34.57, 24, 'Big comfy couch', 50);
insert into parcel_owns (weight, volume, description, customer_id) values (5.57, 14, 'Hockey Stick', 50);
insert into parcel_owns (weight, volume, description, customer_id) values (8.57, 64, 'Yellow Dog', 50);
insert into parcel_owns (weight, volume, description, customer_id) values (7.57, 74, 'All toys', 50);
insert into parcel_owns (weight, volume, description, customer_id) values (6.57, 43, 'Green den', 50);
commit work;
