drop table payment_requires;
drop table contains;
drop table order_delivers;
drop table employee_works;
drop table branch;
drop table parcel_owns;
drop table lives;
drop table customer;
drop table address;
commit;